name = "paper-dash-server"
main = "index.js"
compatibility_date = "2025-10-28"



[[d1_databases]]
binding = "DB" # This is the binding name you'll use in your Worker code
DATABASE_NAME = "paper-dash-db" # The name of your D1 database








[placement]
mode = "off"

# Add this section or modify an existing one
# if you have other compatibility_flags, add "nodejs_compat" to the array
compatibility_flags = ["nodejs_compat_v2"]