name = "paper-dash-server"
main = "dist/src/index.js"
compatibility_date = "2025-10-11"
compatibility_flags = ["nodejs_compat"]


[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true

[build]
command = "npm run build"

[vars]
SERVER_URL="https://paperapi.katundu.org"
NODE_ENV="production"

[[d1_databases]]
binding = "paper_dash_db"
database_name = "paper-dash-db"
database_id = "d6cf09c0-7cc5-4133-bcc7-3b47ffade8b1"
migrations_dir = "drizzle"

[placement]
mode = "off"