name = "paper-dash-server"
main = "dist/src/index.js"
compatibility_date = "2025-10-11"
compatibility_flags = ["nodejs_compat"]

services = [
  { binding = "LOG_API", service = "<logs-monitor-worker>" }
]

# Durable Objects binding
[[durable_objects.bindings]]
name = "TELEGRAM_BOT_DO"
class_name = "TelegramBotDurableObject"
script_name = "paper-dash-server"


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[build]
command = "npm run build"

[vars]
SERVER_URL="https://paperapi.katundu.org"
NODE_ENV="production"
LOGHOG_API_URL = "https://apihog.katundu.org"


[[d1_databases]]
binding = "paper_dash_db"
database_name = "paper-dash-db"
database_id = "d6cf09c0-7cc5-4133-bcc7-3b47ffade8b1"
migrations_dir = "drizzle"

[[migrations]]
tag = "v1_telegram_bot_do"
new_sqlite_classes = ["TelegramBotDurableObject"]

[placement]
mode = "off"